### ISSUE TITLE
LE: Black screen after starting Emulator

### ISSUE THREAD

**Issue by walterheisenberg** [kodi-game/game.libretro.stella#5] opened 2018-03-01 07:20 UTC
I got a black screen after starting the emulator. Even there is no sound.
http://ix.io/QSS
I reported another issue with MrBoom, where I got sound. Don't know the bugs have the same reason or it is just LE :~

PS: I started the ROMs with IARL, but this shouldn't be a problem

**Comment by garbear** [comment] 2018-08-17 23:14
Several black screen fixes have been committed. Is this still an issue?

**Comment by zjoasan** [comment] 2019-02-13 16:20
On pi3 running LE9, i get black screen, but if i punch up the OSD(Game menu) the emulator gets drawn in the background. Sound works even if screen is black.

Same goes for: 
Beetle bsnes
bsnes-mercury Accuracy
bsnes-mercury Balanced
bsnes-mercury Performance
Bettle PSX
Beetle GBA
GBC Sameboy
Nestopia

**Comment by beta-tester** [comment] 2019-02-21 19:49
i can confirm that stella add-on still renders a black screen (LibreELEC 9.0.0 on RPi3B)
and when the "game menu" is opened, then the in-game screen is rendered as dimmed background.
sound is working.

**Comment by garbear** [comment] 2019-02-22 02:28
I believe this is due to OpenGL initializing too early before the fullscreen window opens. I won't have time to look into this for at least the next few weeks, so if you know anyone who wants to do some opengl  debugging I'm eager to guide.

**Comment by djedi23** [comment] 2019-03-17 12:05
I might have found a clue to this issue.
I'm learning libretro core lib to devellop some tiny games on kodi.

My dev env is a pc running ubuntu 18.04.2 LTS with kodi 18.1 installed from the PPA.
My target env is libreelect 9.1 on an rpi3b+ with kodi 18.1.

I'm using XRGB pixel format:
```C
enum retro_pixel_format fmt = RETRO_PIXEL_FORMAT_XRGB8888;
  if (!environ_cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT, &fmt))
```

I have a simple `putpixel` function:
```C
void putpixel(uint32_t *buffer,int x,int y, uint32_t color)
{
  buffer[y*VIDEO_WIDTH +x] = color;
}
```

When I use this line:
```C
      putpixel((uint32_t *)frame_buf,x,y,0xFFFFFFFF);
```
I see a white pixel on the dev env and the target.

Now, if use this line:
```C
      putpixel((uint32_t *)frame_buf,x,y,0x80FFFFFF);
```
I see a white pixel on ubuntu env and a grey pixel on libreelec.


```C
for(int x=0; x<256; x++)
   putpixel((uint32_t *)frame_buf,x,y,(x<<24)+0xFFFFFF);
```
I see a white line on ubuntu env and a gradient line on libreelec.


My interpretation is that on ubuntu the alpha channel is ignored and not on libreelec.

PS: mrboom also displays a black screen on my libreelec.

**Comment by garbear** [comment] 2019-03-21 00:30
I opened this PR with the intention of fixing the problem: https://github.com/xbmc/xbmc/pull/15771

It's been included in the latest milhouse builds. Can someone try it out?

**Comment by Jookia** [comment] 2019-05-16 07:59
@garbear I just tested that PR on a WeTek Play on 18.2, it didn't change anything

**Comment by beta-tester** [comment] 2019-05-16 12:20
@garbear is there an add-on zip file available i can try to install to my LibreELEC 9.0.2 / Kodi 18.2 for my RPi2/3 ?

**Comment by garbear** [comment] 2019-05-19 17:09
No, if @djedi23 is right then the OpenGLES implementation is handling alpha values in a different way than OpenGL. When I get a chance I'll try a fix for @djedi23's testing. It might be a couple weekends before I can get to this, but I'll post back here when I open a PR.

**Comment by Huii** [comment] 2019-06-14 18:16
Hi there,

I'm not sure whether this is the right place to post this but I have the same issue with Mr. Boom on my Raspberry Pi 3 B+ running LibreELEC. I can here the sound and if I press the start button of my controller I see the game in the background but apart from that I can simply see a black screen.

**Comment by smrt28** [comment] 2019-07-01 18:03
Any progress on this issue? I'm really looking forward playing retros on my pie 🙏

**Comment by garbear** [comment] 2019-07-31 07:57
Sent a PR upstream

**Comment by Jookia** [comment] 2019-08-01 09:20
I tested that PR ( #16421 ) and it does solve the issue for me on my WeTek Play. Nice!

**Comment by smrt28** [comment] 2019-08-01 09:26
@Jookia could you please suggest where to download the patched build for rbpi3, thx

**Comment by Jookia** [comment] 2019-08-02 04:02
Sorry @smrt28 I just re-built LibreElec with that PR as two patches.

**Comment by smrt28** [comment] 2019-08-02 04:59
@Jookia thx, I re-built the image and it works. However it's still not usable. Audio seems not working and the dialog claims I need the particular controller which I don't have. I managed to pair kodi with PS3 controller but it was all. It just pairs but doesn't control anything.

**Comment by beta-tester** [comment] 2019-08-02 05:54
@garbear is there an add-on zip file available i can try to install to my LibreELEC 9.0.2 / Kodi 18.2 for my RPi2/3 ?
... thx

**Comment by garbear** [comment] 2019-08-02 17:15
I can provide a .tar update file for LE, would that work for you?

**Comment by beta-tester** [comment] 2019-08-02 21:43
yes, that would be great.
i think i can re-pack the add-on to a zip file to install it...

**Comment by garbear** [comment] 2019-08-02 21:47
The fix is in Kodi, not the add-on

**Comment by beta-tester** [comment] 2019-08-02 22:08
oh, then it is an update to a newer version of kodi?... that's welcome as well.

**Comment by garbear** [comment] 2019-08-03 02:38
This is the version I'm running, https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.0.2

**Comment by beta-tester** [comment] 2019-08-03 12:44
thanks alot... stella is working now very well.

**Comment by Huii** [comment] 2019-08-12 08:26
Unfortunately, this is still not working for me. Even after updating to the newest LibreELEC version on my Pi. Do I have to activate a certain development channel in order to receive the patch? If yes, how would I do so?

**Comment by beta-tester** [comment] 2019-08-12 14:08
@Huii  
> Unfortunately, this is still not working for me. Even after updating to the newest LibreELEC version on my Pi. Do I have to activate a certain development channel in order to receive the patch? 

you have to download the link from post:
> This is the version I'm running, https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.0.2

download/copy that file (LibreELEC-RPi2.arm-9.0-devel-20190801211839-1c74ef3.tar)
to the Update folder on your existing LibreELEC installation
via ssh shell to /storage/.update/
or via samba share \\\\<IP_of_your_RPi>\Update
then simply reboot LibreELEC... it will extract and update your LibreELEC... done.

**Comment by Huii** [comment] 2019-08-13 14:30
@beta-tester Ok, thank you. I'll give that a try.

**Comment by markaspio** [comment] 2019-08-25 09:45
@garbear  I gave a try to your modified version of LibreElec. It solves the Dosbox problem, but it seems to create problems with the other Mame emulators, which don't work or work very slowly.  Reinstalling the latest official version of LibreElec 9.1, Mame emulators return to work correctly, while Dosbox has again the black screen problem.  Thank you

**Comment by garbear** [comment] 2019-08-25 20:33
interesting. should I try building a 9.1 image with the patch?

**Comment by markaspio** [comment] 2019-08-29 09:36
@garbear  I noticed that by installing your 9.0.2 version the system doesn't recognize newer versions of LibreRetro emulators (I came from 9.1, so it was a downgrade for me), and force you to use older versions. Perhaps loading the patch on 9.1 the problem can be solved

**Comment by garbear** [comment] 2019-09-01 23:25
I uploaded a 9.1 release: https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.1-20190901. Tested on my RPi 3 B+ and it works.

**Comment by markaspio** [comment] 2019-09-02 06:30
Great thanks. I will be able to try it again next Saturday when I'll come back home

**Comment by garbear** [comment] 2019-09-08 20:49
get a chance? no rush, undetermined if there will be an 18.5

**Comment by markaspio** [comment] 2019-09-09 06:47
@garbear Im' sorry for the late, I was unable to install your version before 'cause I use Rasberry at my girlfriend home, on weekend. Yesterday I tested it, the situation is this: Dosbox works (and Mr. Boom game also). This time the other emulators remains on last LibreRetro version and they works. BUT they are slow (I tested MAME 2003 Bubble Bobble, AeroFighters 2, Carrier Airwings). I noticed that isn't only the emulated games to be slow, but all the content played with video player: all channels on live tv and videos were slow. I re-installed official LibreElec 9.1 version and all worked fluid and fast (except DOSBOX that doesn't work, of course). So it seems that something on your fix slows down games and reproduced contents... Please note that I installed it on a RPi 3 (not B+). Thanks

**Comment by beta-tester** [comment] 2019-09-18 19:55
hello @garbear,
i just installed the actual official LibreELEC 9.1.501 [9.2 beta1]
(http://releases.libreelec.tv/LibreELEC-RPi2.arm-9.1.501.img.gz)

but in that version the ATARI2600 emulator stellar has still the issue with the black screen.
does it mean that your patch still didn't reached the official repository or how is it possible that it seems to not included in the official beta?

**Comment by garbear** [comment] 2019-09-18 20:55
@beta-tester you will need a build that includes https://github.com/xbmc/xbmc/pull/16421. I linked to a test build earlier where I included the PR.

**Comment by beta-tester** [comment] 2019-09-19 04:40
oops, sorry, i overlooked or forgot,
that it is an issue in Kodi...
so as long LibreELEC is using the unpatched/unfixed Kodi (<=18.4), the issue will stay.

**Comment by renedonaire** [comment] 2019-09-30 01:18
@garbear  I got an error when I try this procedure, ".tar file is corrupted"
Do you have an alternate download link?

> download/copy that file (LibreELEC-RPi2.arm-9.0-devel-20190801211839-1c74ef3.tar)
> to the Update folder on your existing LibreELEC installation
> via ssh shell to /storage/.update/
> or via samba share \\<IP_of_your_RPi>\Update
> then simply reboot LibreELEC... it will extract and update your LibreELEC... done.

**Comment by garbear** [comment] 2019-10-28 04:16
@renedonaire I rebuilt the image against the latest branches: https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.1-20191027

**Comment by garbear** [comment] 2019-10-29 00:40
The feedback I've gotten is positive, minus the video slowdown due to using LE master instead of the RPi branch. Is the fix in https://github.com/xbmc/xbmc/pull/16421 good to go?

**Comment by beta-tester** [comment] 2019-10-29 08:49
i only can tell that i don't have the blackscreen issue with the "v9.1-20191027" image on a RPi3B.
about slowing down issue i can't tell anything about it, because i did not notice that before.
i didn't used those specific emulators or live-video.

**Comment by beta-tester** [comment] 2019-10-29 09:10
oops, i tried out "Arcade (MAME 2003)" with "bombjack.zip"
and i can observe some strange timing issues. sound and gameplay get stuck and after that it continues with higher speed than normal. starts after the first time i "died" in the game.
it can not be a thermal throttle down issue.
the same bombjack.zip i can play with "Arcade (FB Alpha)" without any problems. there it plays smooth with no issues.

**Comment by garbear** [comment] 2019-10-30 20:54
I'm going to consider the slowdown unrelated (and due to missing LE-specific patches). If blackscreen still works in the `2019-10-27` image then I think that https://github.com/xbmc/xbmc/pull/16421 can be merged.

**Comment by renedonaire** [comment] 2019-11-04 01:01
> @garbear I got an error when I try this procedure, ".tar file is corrupted"
> Do you have an alternate download link?
> 
> > download/copy that file (LibreELEC-RPi2.arm-9.0-devel-20190801211839-1c74ef3.tar)
> > to the Update folder on your existing LibreELEC installation
> > via ssh shell to /storage/.update/
> > or via samba share \<IP_of_your_RPi>\Update
> > then simply reboot LibreELEC... it will extract and update your LibreELEC... done.

@garbear Thank you! Loaded the new .tar file and updated succesfully. Everything working OK, blackscreen issue fixed.
After this, I should keep the LibreElec updates preferences in "manual" mode or I should turn it to "auto" mode?

**Closed as completed** 2019-11-17 08:02 UTC

**Comment by beta-tester** [comment] 2019-11-22 16:32
will the fix be in Kodi 18.5 already or at least in the LibreELEC 9.2 release?
because i can't see anything about this fix in the changelog of Kodi 18.5.

**Comment by garbear** [comment] 2019-11-23 00:44
When I get a chance I'll backport the fix to 18.6.

**Comment by beta-tester** [comment] 2019-11-26 18:37
not really sure what "backport the fix to 18.6" exactly means.
the current official release LibreELEC 9.2 for RPi3 has Kodi 18.5.
is there a detailed step-by-step tutorial available how to compile/build the LibreELEC 9.2 update with the fixed Kodi 18.6 by myself?

**Comment by garbear** [comment] 2019-11-27 04:31
> not really sure what "backport the fix to 18.6" exactly means.

You'll notice this PR is against master. When we released 18.0, we "branched" the code, and "porting" means to take a PR against one branch an apply it to another. A "backport" is when the other branch is older, so this fix will be PRed to our `Leia` branch and included when we release 18.6.

I had to piece together several tutorials to learn how to compile LE, but now that I'm up and running, I can make a RPi3 build with LE 9.2 and Kodi 18.5 plus this patch (there's no other changes for 18.6 yet). I uploaded the build here: https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.2-20191126

**Comment by beta-tester** [comment] 2019-11-27 05:30
again, thank you very much !!!

**Comment by cworth33** [comment] 2020-01-02 09:40
I just ran into similar issues with the blank screen when attempting to run games from Kodi using 
I'd like to put this pre release 18.6 build on my RPi3 but not sure where to get the artifacts or how to do a CLI update from pre release branch.  Any help?

**Comment by garbear** [comment] 2020-01-03 00:02
Can't you just copy the release to the "Update" share?

**Comment by beta-tester** [comment] 2020-03-14 11:45
with official LibreELEC 9.2.1, stella is working
thanks.

**Comment by JORGETECH** [comment] 2021-11-20 17:26
I'm experiencing this issue in LibreELEC 10.0.1 (Official) running in the Orange Pi Lite2 (Allwinner H6 with Panfrost GPU). So far I encountered it on Stella, Gambatte, and mGBA cores.

Is this a regression in Matrix?

EDIT: In my case it displays the game for a short time until I get a black screen. As it was mentioned in the original issue, I can only see the contents of the emulator when I access the menu.

**Comment by garbear** [comment] 2021-11-20 21:26
I haven't come across this problem in my testing. It might be a new issue. Can you upload a debug log?

**Comment by svpudik** [comment] 2022-06-10 06:59
I have that issue on Orange pi 3 with LibreELEC 10.0.2 H6.arm architecture. Strange is, when I start logging it works properly. Probably because of that logging text in left top corner which keeps screen on. Does not matter which launcher I use.

**Comment by garbear** [comment] 2022-06-10 22:35
Likely a GLES quirk that doesn't save the screen contents unless there's a dirty-region update. @lrusak @a1rwulf @sarbes any ideas?

**Comment by a1rwulf** [comment] 2022-06-17 04:07
No idea sorry.

**Comment by LemanRus** [comment] 2022-09-22 05:25
I got the same problem on Orange Pi 3 (Alwinner H6) with LibreELEC 10.0.2. Doesn't matter which emulator I use - black screen appears after few seconds after starting the game. Sound is OK and I can see the game content when I access the menu, as @JORGETECH.

**Comment by antonic901** [comment] 2022-10-20 23:05
I also have same problem. I'm running Tanix TX6 with Allwinner H6. I tried SNES, Nestopia and Genesis emulators and on all of them blank screen with sound in background. I can only see content of emulator when I open pause menu (Select + X). On Kodi inside Android this problem is not persistent.

**Comment by beta-tester** [comment] 2022-10-21 08:25
with LibreELEC 10.0.2/10.0.3 on my RPi 3B+, i have **no** black screen or sound issues with **Stella** (ATARI2600) emulator.
everything shows and plays well in Stella.

### PS.:
i have a black screen issue with **Vectrex** emulator.
sound is ok for the intro but get stuck later on.
no in-game picture of the screen at pause.

but i have other issues with LibreELEC 10.0.2/10.0.3 on my RPi 3B+:
- **Sega - MS/GG/MD/CD (Genesis Plus GX)**: Seag Game Gear (*.gg) and Sega Master Systems (*.sms) games are not working - the emulator does crash LibreELEC, when trying so load a game.
Seaga Genesis (*.md) games are working.
**Seage - MS/MD/CD/32X (PicoDrive)**: Sega Master Systems (*.sms) games are working.
- **Vectrex**: isn't usable at all - black screen. sound only for few seconds of the intro but then it get stuck. the emulator does not crash LibreELEC.
- **Sony - Playstation (PCX ReARMed)**: games do not start - nothing happens after reset a game. while resuming old paused games are kind of working.

everything above was working well at LibreELEC 9.2.8 (maybe with patched version of Vectrex)
